create table if not exists daily_verdicts (
    id uuid primary key default gen_random_uuid(),
    date date unique not null,
    verdict text,
    strike_count integer,
    strikes_triggered jsonb,
    regime_label text,
    regime_confidence float,
    yield_bps_change float,
    yield_accelerating boolean,
    smh_vs_spy float,
    smh_vs_qqq float,
    semi_health_score float,
    semi_health_label text,
    vix_term_structure text,
    realized_vs_implied float,
    smh_iv float,
    nvda_iv float,
    smh_iv_elevated boolean,
    nvda_iv_elevated boolean,
    gex_value float,
    gex_label text,
    gex_key_level_mnq float,
    semi_sentiment_score float,
    macro_sentiment_score float,
    top_headlines jsonb,
    high_impact_event_today boolean,
    event_names jsonb,
    earnings_flag boolean,
    guidance_cut_flag boolean,
    expected_range_low float,
    expected_range_high float,
    one_sigma_low float,
    one_sigma_high float,
    verdict_reason text,
    created_at timestamptz default now()
);

create index if not exists daily_verdicts_date_idx on daily_verdicts (date);
